#    Distributed Vector-OLE Generator
#    Copyright (C) 2019 Phillipp Schoppmann and Adria Gascon
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

# The local_repository only works when this is a subfolder of the distributed_vector_ole repository.
local_repository(
    name = "distributed_vector_ole",
    path = "..",
)

## When using this example as a basis for your own workspace, replace the above by this http_archive instead:
#http_archive(
#    name = "distributed_vector_ole",
#    strip_prefix = "distributed-vector-ole-master",
#    url = "https://github.com/schoppmp/distributed-vector-ole/archive/master.zip",
#)

load("@distributed_vector_ole//distributed_vector_ole:preload.bzl", "distributed_vector_ole_preload")

distributed_vector_ole_preload()

load("@distributed_vector_ole//distributed_vector_ole:deps.bzl", "distributed_vector_ole_deps")

distributed_vector_ole_deps()

load("@io_bazel_rules_docker//repositories:pip_repositories.bzl", "pip_deps")

pip_deps()