variables:
  REGISTRY: gitlab.informatik.hu-berlin.de:4567

build_archlinux:
  image: archlinux/base
  stage: build
  tags:
    - aes  # Needed for running tests.
  before_script:
    - pacman -Syu --noconfirm base-devel bazel git python python2 cmake
    - echo "build --remote_http_cache=https://${CACHE_USER}:${CACHE_PASSWORD}@bazel-remote-cache.informatik.hu-berlin.de:9090" >> ~/.bazelrc
  script:
    - bazel build ...
    - bazel test ...
  after_script:
    - mkdir logs && cp -rL bazel-testlogs/* logs  # Artifacts have to be in the workspace, but bazel-testlogs is a symlink that points outside of it.
  artifacts:
    when: always
    paths:
      - logs

build_ubuntu:
  image: ubuntu:18.04
  stage: build
  tags:
    - aes  # Needed for running tests.
  before_script:
    - apt-get update
    - apt-get install -y build-essential python python3 git gnupg2 curl patch m4 cmake
    - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
    - curl https://bazel.build/bazel-release.pub.gpg | apt-key add -
    - apt-get update && apt-get install -y bazel
    - echo "build --remote_http_cache=https://${CACHE_USER}:${CACHE_PASSWORD}@bazel-remote-cache.informatik.hu-berlin.de:9090" >> ~/.bazelrc
  script:
    - bazel build ...
    - bazel test ...
  after_script:
    - mkdir logs && cp -rL bazel-testlogs/* logs  # Artifacts have to be in the workspace, but bazel-testlogs is a symlink that points outside of it.
  artifacts:
    when: always
    paths:
      - logs

deploy:
  image: archlinux/base
  stage: deploy
  before_script:
    - pacman -Syu --noconfirm base-devel bazel git python python2 cmake docker
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - echo "build --remote_http_cache=https://${CACHE_USER}:${CACHE_PASSWORD}@bazel-remote-cache.informatik.hu-berlin.de:9090" >> ~/.bazelrc
  script:
    - bazel run -c opt --//experiments:docker_deploy_tag=$CI_COMMIT_SHA //experiments:deploy_hu
    - bazel run -c opt --//experiments:docker_deploy_tag=$CI_COMMIT_REF_SLUG //experiments:deploy_hu
    - if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
        bazel run -c opt --//experiments:docker_deploy_tag=latest //experiments:deploy_hu;
      fi