variables:
  REGISTRY: gitlab.informatik.hu-berlin.de:4567

build_archlinux:
  image: archlinux/base
  stage: build
  tags:
    - aes
  before_script:
    - pacman -Syu --noconfirm base-devel bazel git python python2 cmake boost
  script:
    - bazel build ...
    - bazel test ...
    - mkdir logs && cp -rL bazel-testlogs/* logs  # Artifacts have to be in the workspace, but bazel-testlogs is a symlink that points outside of it.
  artifacts:
    when: always
    paths:
      - logs

build_ubuntu:
  image: ubuntu:18.04
  stage: build
  tags:
    - aes
  before_script:
    - apt-get update
    - apt-get install -y build-essential openjdk-11-jdk gnupg2 curl patch m4 cmake libboost-all-dev
    - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
    - curl https://bazel.build/bazel-release.pub.gpg | apt-key add -
    - apt-get update && apt-get install -y bazel
  script:
    - bazel build ...
    - bazel test ...
    - mkdir logs && cp -rL bazel-testlogs/* logs  # Artifacts have to be in the workspace, but bazel-testlogs is a symlink that points outside of it.
  artifacts:
    when: always
    paths:
      - logs

deploy:
  image: docker:stable
  stage: deploy
  tags:
    - dockerimage
  services:
    - docker:dind  # Needed until container_push works (https://github.com/google/containerregistry/issues/42)
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
  script:
    - docker run --rm
        -e CACHE_USER="$CACHE_USER"
        -e CACHE_PASSWORD="$CACHE_PASSWORD"
        -v /var/run/docker.sock:/var/run/docker.sock
        -v "$PWD":/data "$REGISTRY"/ti/software/bazel-builder:latest
        "cd /data && bazel run -c opt //experiments:deploy"
    - docker images --format "{{.Repository}} {{.Tag}}"
      | grep -E "^$REGISTRY/$CI_PROJECT_PATH"
      | grep -E 'latest$'
      | cut -d" " -f1
      | while read image; do
          docker tag $image $image:$CI_COMMIT_SHA;
          docker tag $image $image:$CI_COMMIT_REF_SLUG;
          docker push $image:$CI_COMMIT_SHA;
          docker push $image:$CI_COMMIT_REF_SLUG;
          if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
            docker push $image:latest;
          fi;
        done;
